"""Candidate generation (blocking) via a multi-pass, vectorized inverted-index join.

Blocking is the recall ceiling for the whole pipeline (see problem statement): a true
match excluded here can never be recovered downstream. At the same time a full
Cartesian product between Source 1 (millions of rows) and Source 2/3 (millions of
rows each) is infeasible, so candidates are generated by joining on shared "blocking
keys" (name tokens, name prefixes, address digit tokens, address tokens) instead of
comparing every pair directly.

Implementation strategy: build a long "(entity_id, key_type, key) exploded" table for
each side, restrict the join to same-country pairs (country is treated as an open
string label — see normalization.country_normalized), and use a pandas hash-merge
per (key_type, country) instead of Python-level nested loops. Overly common keys
(e.g. "inc", "road") are dropped before the join because they would otherwise blow up
the join's row count without adding discriminative signal — a standard blocking
technique ("stop-token" pruning).
"""

from __future__ import annotations

import pandas as pd

from resolvex import normalization as norm
from resolvex.config import (
    MAX_BLOCK_KEY_POSTING_LIST,
    MAX_CANDIDATES_PER_ENTITY,
    MIN_BLOCKING_TOKEN_LEN,
)

# Upper bound on (left_count * right_count) for a single blocking key within a single
# country partition. Bounds the number of candidate-pair rows a single key can
# contribute to the join, regardless of how the count is split between sides.
MAX_KEY_PAIR_PRODUCT = 50_000

_ADDRESS_STOPWORDS = {
    "street",
    "road",
    "avenue",
    "drive",
    "lane",
    "court",
    "place",
    "square",
    "highway",
    "parkway",
    "apartment",
    "building",
    "floor",
    "suite",
    "north",
    "south",
    "east",
    "west",
    "number",
    "near",
    "unit",
}


def _prep(df: pd.DataFrame) -> pd.DataFrame:
    """Attach normalized token/key columns to a source DataFrame (copy)."""
    out = df[["entity_id"]].copy()
    out["country_norm"] = norm.country_normalized(df["country"])
    out["name_tokens"] = norm.normalized_name_tokens(df["business_name"])
    out["addr_tokens"] = norm.normalized_address_tokens(df["business_address"])
    out["digit_tokens"] = norm.extract_digit_tokens(df["business_address"])
    return out


def _explode_keys(prepped: pd.DataFrame) -> pd.DataFrame:
    """Build the long (entity_id, country_norm, key_type, key) table.

    Four key types are emitted:
    - ``name_token``: individual name tokens (len >= MIN_BLOCKING_TOKEN_LEN)
    - ``name_prefix``: first 4 alphanumeric characters of the normalized name —
      robust to trailing typos/suffix differences
    - ``addr_digit``: numeric tokens from the address (house numbers, PIN/ZIP codes)
    - ``addr_token``: address tokens excluding generic street-type stopwords
    """
    frames = []

    name_tok = prepped[["entity_id", "country_norm", "name_tokens"]].explode("name_tokens")
    name_tok = name_tok.rename(columns={"name_tokens": "key"}).dropna(subset=["key"])
    name_tok = name_tok[name_tok["key"].str.len() >= MIN_BLOCKING_TOKEN_LEN]
    name_tok["key_type"] = "name_token"
    frames.append(name_tok)

    prefix = prepped[["entity_id", "country_norm", "name_tokens"]].copy()
    prefix["key"] = prefix["name_tokens"].apply(
        lambda toks: "".join(toks)[:4] if toks else ""
    )
    prefix = prefix[prefix["key"].str.len() >= 4][["entity_id", "country_norm", "key"]]
    prefix["key_type"] = "name_prefix"
    frames.append(prefix)

    digits = prepped[["entity_id", "country_norm", "digit_tokens"]].explode("digit_tokens")
    digits = digits.rename(columns={"digit_tokens": "key"}).dropna(subset=["key"])
    digits = digits[digits["key"].str.len() >= 3]
    digits["key_type"] = "addr_digit"
    frames.append(digits)

    addr_tok = prepped[["entity_id", "country_norm", "addr_tokens"]].explode("addr_tokens")
    addr_tok = addr_tok.rename(columns={"addr_tokens": "key"}).dropna(subset=["key"])
    addr_tok = addr_tok[
        (addr_tok["key"].str.len() >= MIN_BLOCKING_TOKEN_LEN)
        & (~addr_tok["key"].isin(_ADDRESS_STOPWORDS))
        & (~addr_tok["key"].str.isdigit())
    ]
    addr_tok["key_type"] = "addr_token"
    frames.append(addr_tok)

    long_df = pd.concat(frames, ignore_index=True)
    long_df = long_df[long_df["key"] != ""]
    long_df = long_df.reset_index(drop=True)
    # Categorical dtype turns the downstream groupby/merge keys into integer-code
    # comparisons instead of full string hashing/comparison — this matters a lot
    # once these tables run into tens of millions of rows.
    for col in ("key_type", "country_norm", "key"):
        long_df[col] = long_df[col].astype("category")
    return long_df


def _prune_common_keys(
    left_long: pd.DataFrame, right_long: pd.DataFrame
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Drop (key_type, country, key) groups whose left*right count would blow up the join."""
    group_cols = ["key_type", "country_norm", "key"]
    left_counts = left_long.groupby(group_cols, observed=True).size().rename("left_n")
    right_counts = right_long.groupby(group_cols, observed=True).size().rename("right_n")

    # Hard per-side cap: a key posting list longer than this on either side is too
    # generic to be discriminative (e.g. common legal-suffix remnants).
    left_counts = left_counts[left_counts <= MAX_BLOCK_KEY_POSTING_LIST]
    right_counts = right_counts[right_counts <= MAX_BLOCK_KEY_POSTING_LIST]

    joined = pd.concat([left_counts, right_counts], axis=1, join="inner")
    joined = joined[joined["left_n"] * joined["right_n"] <= MAX_KEY_PAIR_PRODUCT]
    keep_index = joined.index

    left_long = left_long.set_index(group_cols)
    right_long = right_long.set_index(group_cols)
    left_kept = left_long.loc[left_long.index.isin(keep_index)].reset_index()
    right_kept = right_long.loc[right_long.index.isin(keep_index)].reset_index()
    return left_kept, right_kept


# Rough informativeness weight per key type — rarer/higher-precision key types score
# more when a candidate is ranked before truncation to MAX_CANDIDATES_PER_ENTITY.
_KEY_TYPE_WEIGHT = {
    "addr_digit": 3.0,
    "name_token": 1.5,
    "name_prefix": 1.0,
    "addr_token": 1.0,
}


def _join_one_side(
    s1_long: pd.DataFrame, other_long: pd.DataFrame, other_source_label: str
) -> pd.DataFrame:
    """Inner-join S1 keys against one other source's keys; return scored pairs."""
    s1_kept, other_kept = _prune_common_keys(s1_long, other_long)
    if s1_kept.empty or other_kept.empty:
        return pd.DataFrame(columns=["source1_entity_id", "candidate_entity_id", "weight"])

    merged = s1_kept.merge(
        other_kept,
        on=["key_type", "country_norm", "key"],
        suffixes=("_s1", "_other"),
    )
    merged["weight"] = merged["key_type"].map(_KEY_TYPE_WEIGHT).astype(float)
    scored = (
        merged.groupby(["entity_id_s1", "entity_id_other"], observed=True)["weight"]
        .sum()
        .reset_index()
        .rename(
            columns={
                "entity_id_s1": "source1_entity_id",
                "entity_id_other": "candidate_entity_id",
            }
        )
    )
    scored["source"] = other_source_label
    return scored


def generate_candidates(
    s1_df: pd.DataFrame,
    s2_df: pd.DataFrame,
    s3_df: pd.DataFrame,
    max_candidates: int = MAX_CANDIDATES_PER_ENTITY,
) -> pd.DataFrame:
    """Generate the final candidate set: one row per (source1_entity_id, candidate_entity_id, score).

    Every Source 1 entity_id appears at least implicitly (entities with zero
    candidates simply have no rows here — the caller fills them in as empty when
    writing candidate_pairs.tsv).
    """
    s1_prepped = _prep(s1_df)
    s2_prepped = _prep(s2_df)
    s3_prepped = _prep(s3_df)

    s1_long = _explode_keys(s1_prepped)
    s2_long = _explode_keys(s2_prepped)
    s3_long = _explode_keys(s3_prepped)

    pairs_s2 = _join_one_side(s1_long, s2_long, "S2")
    pairs_s3 = _join_one_side(s1_long, s3_long, "S3")
    all_pairs = pd.concat([pairs_s2, pairs_s3], ignore_index=True)

    if all_pairs.empty:
        return all_pairs.assign(source1_entity_id=[], candidate_entity_id=[], weight=[])

    all_pairs = all_pairs.sort_values("weight", ascending=False)
    all_pairs["rank"] = all_pairs.groupby("source1_entity_id", observed=True).cumcount()
    all_pairs = all_pairs[all_pairs["rank"] < max_candidates].drop(columns="rank")
    return all_pairs.reset_index(drop=True)
